services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  YoastSeoForTypo3\YoastSeo\:
    resource: '../Classes/*'

  YoastSeoForTypo3\YoastSeo\EventListener\TcaBuiltListener:
    arguments:
      - '@YoastSeoForTypo3\YoastSeo\Record\Builder\TcaBuilder'
    tags:
      - name: event.listener
        identifier: 'yoastTca'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
        method: 'addRecordTca'

  YoastSeoForTypo3\YoastSeo\EventListener\TableDefinitionsListener:
    arguments:
      - '@YoastSeoForTypo3\YoastSeo\Record\Builder\SchemaBuilder'
    tags:
      - name: event.listener
        identifier: 'yoastSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
        method: 'addDatabaseSchema'

  YoastSeoForTypo3\YoastSeo\EventListener\RecordCanonicalListener:
    arguments:
      - '@TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController'
      - '@YoastSeoForTypo3\YoastSeo\Record\RecordService'
    tags:
      - name: event.listener
        identifier: 'yoastRecordCanonical'
        event: TYPO3\CMS\Seo\Event\ModifyUrlForCanonicalTagEvent
        method: 'setCanonical'

  YoastSeoForTypo3\YoastSeo\PageTitle\RecordPageTitleProvider:
    arguments:
      - '@YoastSeoForTypo3\YoastSeo\Record\RecordService'

  YoastSeoForTypo3\YoastSeo\MetaTag\RecordMetaTagGenerator:
    arguments:
      - '@YoastSeoForTypo3\YoastSeo\Record\RecordService'
